cargo run --\
  --station phraram9\
  --station samyan\
  --station thonburi\
  --station silom\
  --route r1,silom,thonburi,30\
  --route r2,silom,thonburi,10\
  --route r3,silom,thonburi,10\
  --package food,5,phraram9,samyan\
  --package clothes,5,thonburi,silom\
  --train alpha,2,1\
  --train beta,2,2\
